package ua.zxcode.sololevelingapp.presentation.home

object QuestExercises {
    val list = listOf(
        "3/4 ситапи (3/4 sit-up)",
        "Аб-ролик (Ab Roller)",
        "Автомобільне кермо (Car driver)",
        "Альпініст (Mountain climber)",
        "Армійський жим штанги (Barbell Shoulder Press / Military press)",
        "Арнольд прес (Arnold press)",
        "Берпі (Burpee)",
        "Біг на біговій доріжці (Treadmill running)",
        "Біг на місці (Jog In Place)",
        "Біг підтюпцем на доріжці (Treadmill jogging)",
        "Бокові нахили з гантеллю (Dumbbell side bend)",
        "Бокові підтягування (Side To Side Chins)",
        "Боротьба з канатами (Battle ropes)",
        "Велосипед для преса (Ab bicycle)",
        "Велосипедна їзда (Bicycling)",
        "Велотренажер (Stationary bike)",
        "Випади вперед (Forward lunge)",
        "Випади зі штангою в русі (Barbell walking lunge)",
        "Випади назад з гантелями (Dumbbell reverse lunge)",
        "Випади на місці з гантелями (Dumbbell Lunges)",
        "Вихід силою (Muscle Up)",
        "Віджимання від лавки з піднятими ногами (Feet-elevated bench dip)",
        "Віджимання від підлоги (Pushups / Push-Ups)",
        "Віджимання від підлоги з піднятими ногами (Feet-elevated push-up)",
        "Віджимання від підлоги з руками на підвищенні (Hands-elevated push-up)",
        "Віджимання від підлоги з фітболом під ногами (Push-Ups With Feet On An Exercise Ball)",
        "Віджимання в стійці на руках (Handstand push-up)",
        "Віджимання вузьким хватом на трицепс (Push-Ups - Close Triceps Position)",
        "Віджимання на брусах для грудей (Chest dip)",
        "Віджимання на брусах на трицепс (Triceps dip)",
        "Віджимання на кільцях (Ring dip)",
        "Віджимання на похилій поверхні (Incline Push-Up)",
        "Віджимання широким-вузьким хватом по черзі (Close push-up to wide push-up)",
        "Вправи на шию лежачи горілиць з диском (Lying Face Up Plate Neck Resistance)",
        "Вправи на шию лежачи ниць з диском (Lying Face Down Plate Neck Resistance)",
        "Вправа гусениця (Spider crawl)",
        "Вправа кокон (Cocoons)",
        "Вправа мертвий жук (Dead bug reach)",
        "Гіперекстензія (Back extension)",
        "Гіперекстензія без тренажера (Hyperextensions With No Hyperextension Bench)",
        "Глухі підтягування на біцепс (EZ-bar spider curl)",
        "Горилла кранч/підтягування (Gorilla Chin/Crunch)",
        "Грубі стрибки в довжину (Broad jump)",
        "Дворучний армійський жим гир (Two-Arm Kettlebell Military Press)",
        "Джампінг джеки (Jumping jack)",
        "Діп-тренажер (Dip Machine)",
        "Драг згинання рук на біцепс (Drag curl)",
        "Жим Арнольда (Arnold press)",
        "Жим гантелей лежачи (Dumbbell Bench Press)",
        "Жим гантелей на похилій лаві (Incline dumbbell bench press)",
        "Жим гантелей на похилій лаві хватом долонями всередину (Incline Dumbbell Bench With Palms Facing In)",
        "Жим гантелей на спадаючій лаві (Decline dumbbell bench press)",
        "Жим гантелей сидячи (Seated Dumbbell Press)",
        "Жим гантелей стоячи (Standing dumbbell shoulder press)",
        "Жим з підлоги з гантелями (Dumbbell floor press)",
        "Жим ногами (Leg Press)",
        "Жим ногами вузькою постановкою (Narrow-stance leg press)",
        "Жим плечима в тренажері (Smith machine shoulder press)",
        "Жим сидячи в тренажері (Seated cable shoulder press)",
        "Жим штанги з-за голови стоячи (Standing Bradford press)",
        "Жим штанги лежачи (Barbell Bench Press)",
        "Жим штанги лежачи середнім хватом (Barbell Bench Press - Medium Grip)",
        "Жим штанги лежачи широким хватом (Wide-grip bench press)",
        "Жим штанги на похилій лаві (Barbell Incline Bench Press Medium-Grip)",
        "Жим штанги на спадаючій лаві (Decline barbell bench press)",
        "Жим штанги сидячи (Seated barbell shoulder press)",
        "Жим штанги стоячи (Barbell Shoulder Press)",
        "Жим штанги шиї (Neck Press)",
        "Застрибування на тумбу (Box jump)",
        "Згинання рук з гантелями молотковим хватом (Hammer Curls / Cross-body hammer curl)",
        "Згинання рук з гантелями на біцепс (Dumbbell Bicep Curl)",
        "Згинання рук з гантелями сидячи (Seated dumbbell biceps curl)",
        "Згинання рук з гантелями стоячи хватом долонями вгору (Standing One-Arm Dumbbell Curl Over Incline Bench)",
        "Згинання рук з гирями поперемінно (Alternating Kettlebell Press)",
        "Згинання рук Зоттмана (Zottman Curl)",
        "Згинання рук на біцепс концентровані (Concentration curl)",
        "Згинання рук на біцепс на похилій лаві (Incline Hammer Curls / Alternate Incline Dumbbell Curl)",
        "Згинання рук на біцепс поперемінно лежачи на похилій лаві (Alternating incline dumbbell biceps curl)",
        "Згинання рук на біцепс стоячи (Dumbbell Alternate Bicep Curl)",
        "Згинання рук на біцепс у тренажері (Machine Bicep Curl)",
        "Згинання рук на блоці стоячи (Standing Biceps Cable Curl)",
        "Згинання рук на лаві Скотта (Preacher Curl)",
        "Згинання рук на лаві Скотта з гантелями молотковим хватом (Preacher Hammer Dumbbell Curl)",
        "Згинання рук на лаві Скотта концентровані вузьким хватом (Seated Close-Grip Concentration Barbell Curl)",
        "Згинання рук на лаві Скотта зворотним хватом (Reverse Barbell Preacher Curls)",
        "Згинання рук зі штангою на біцепс (Barbell Curl)",
        "Згинання рук зі штангою лежачи на похилій лаві (Barbell Curls Lying Against An Incline)",
        "Згинання рук зі штангою зворотним хватом (Reverse Cable Curl)",
        "Згинання рук зі штангою широким хватом (Wide-grip barbell curl)",
        "Згинання рук зі штангою вузьким хватом (Close-grip barbell curl)",
        "Згинання рук з EZ-штангою (EZ-Bar Curl)",
        "Згинання рук з EZ-штангою вузьким хватом (Close-grip EZ-bar curl)",
        "Згинання рук з EZ-штангою зворотним хватом (Flexor Incline Dumbbell Curls)",
        "Згинання рук однією рукою з гантеллю на лаві Скотта (Single-arm dumbbell preacher curl)",
        "Згинання рук однією рукою на нижньому блоці стоячи (Standing One-Arm Cable Curl)",
        "Згинання рук у кросовері над головою (Overhead cable curl)",
        "Згинання пальців сидячи (Seated finger curl)",
        "Згинання зап'ясть долонями вниз на лаві (Palms-down wrist curl over bench)",
        "Згинання зап'ясть долонями вгору на лаві (Palms-up wrist curl over bench / Seated palms-up wrist curl)",
        "Згинання зап'ясть стоячи за спиною (Standing behind-the-back wrist curl)",
        "Згинання зап'ясть двома руками на нижньому блоці долонями вгору (Seated Two-Arm Palms-Up Low-Pulley Wrist Curl)",
        "Згинання зап'ясть однією рукою з гантеллю долонями вгору (Seated One-Arm Dumbbell Palms-Up Wrist Curl)",
        "Згинання зап'ясть однією рукою з гантеллю долонями вниз (Seated One-Arm Dumbbell Palms-Down Wrist Curl)",
        "Згинання зап'ясть зі штангою долонями вниз сидячи (Seated Palms-Down Barbell Wrist Curl)",
        "Згинання зап'ясть з гантелями долонями вгору на лаві (Palms-Up Dumbbell Wrist Curl Over A Bench / Palms-Down Dumbbell Wrist Curl Over A Bench)",
        "Зворотні скручування (Reverse crunch)",
        "Зворотні скручування на лаві (Decline reverse crunch / Decline oblique crunch)",
        "Зворотні віджимання на лаві (Weighted bench dip)",
        "Зворотна тяга штанги в нахилі (Yates Row Reverse Grip)",
        "Зовнішня ротація плеча з кабелем (External Rotation with Cable)",
        "Камені Атласа (Atlas Stones)",
        "Кардіо степпер (Stairmaster / Stair climber)",
        "Книжка (складочка на прес) (V-up)",
        "Козацькі присідання / Гройнери (Groiners)",
        "Колесико для преса на колінах (Barbell Ab Rollout - On Knees / Barbell roll-out)",
        "Комплексна вправа Мен-мейкер (Man-maker)",
        "Кранчі лежачи з піднятими руками (Crunch - Hands Overhead)",
        "Кранчі на прес (Crunches)",
        "Кранчі на спадаючій лаві (Decline Crunch)",
        "Кранчі на спадаючій лаві з вагою (Weighted Crunches)",
        "Кранчі на колінах на блоці (Kneeling cable crunch / Kneeling cable oblique crunch / Kneeling Cable Crunch With Alternating Oblique Twists / Rope Crunch)",
        "Кранчі на фітболі (Exercise ball crunch / Exercise Ball Pull-In)",
        "Кранчі лікоть-коліно (Elbow-to-knee crunch / Cross-Body Crunch)",
        "Кранчі з підтягуванням колін на плоскій лаві (Seated Flat Bench Leg Pull-In)",
        "Кранчі на прес з підтягуванням ніг (Knees tucked crunch)",
        "Кросовер на кабелі (Cable cross-over)",
        "Кросовер з низького блоку (Low-cable cross-over)",
        "Кругові рухи стегнами лежачи (Hip Circles (Prone))",
        "Кругові рухи стегнами стоячи (Standing Hip Circles)",
        "Лазіння по канату (Rope climb)",
        "Легкі нахили гуд морнінг (Good Morning)",
        "Махи гантелями в сторони сидячи (Seated Side Lateral Raise)",
        "Махи гантелями в сторони стоячи (Side Lateral Raise)",
        "Махи гантелями в нахилі назад (Dumbbell Lying Rear Lateral Raise)",
        "Махи гантелями перед собою (Dumbbell front raise)",
        "Махи гантелями перед собою на похилій лаві (Incline dumbbell front raise)",
        "Махи гантелями перед собою в сторони по черзі (Dumbbell front raise to lateral raise)",
        "Махи диском перед собою (Front Plate Raise)",
        "Махи диском перед собою з пуловером (Front Raise And Pullover)",
        "Махи однією рукою в нахилі назад на похилій лаві (Single-arm incline rear delt raise)",
        "Махи однією рукою перед собою на блоці (Single-arm cable front raise)",
        "Махи однією рукою в сторону (Single-arm lateral raise)",
        "Махи однією рукою в нахилі на блоці (Single-arm bent-over cable rear delt fly)",
        "Махи однією рукою на похилій лаві в сторону (Single-arm incline lateral raise)",
        "Махи однією рукою з гантеллю перед собою по черзі (Alternating dumbbell front raise)",
        "Махи гантелями перед собою по черзі (Alternating Deltoid Raise)",
        "Махи гантеллю перед собою (Single-dumbbell front raise)",
        "Махи гантелями назад на похилій лаві (Incline dumbbell reverse fly)",
        "Махи плечима зі штангою (Barbell shrug / Middle Back Shrug)",
        "Махи плечима в тренажері Сміта (Smith machine shrug)",
        "Махи плечима на важелі (Leverage Shrug)",
        "Махи плечима з гантелями (Standing dumbbell shrug)",
        "Махи плечима в тренажері на литки (Calf Press On The Leg Press Machine / Calf-Machine Shoulder Shrug)",
        "Мертва тяга зі штангою (Barbell Deadlift)",
        "Мертва тяга штанги з дефіциту (Barbell deficit deadlift)",
        "Мертва тяга штанги широким хватом (Snatch Deadlift)",
        "Мертва тяга штанги з резинками (Deadlift with Bands)",
        "Мертва тяга штанги з ланцюгами (Deadlift with Chains)",
        "Мертва тяга штанги з плінтов (Clean Deadlift)",
        "Мертва тяга з треп-грифом (Hex-bar deadlift)",
        "Мисливська собака / прес (Dead bug reach)",
        "Молотки з гантелями (Hammer Curls / Cross-body hammer curl)",
        "М'язові виходи силою на брусах чи кільцях (Muscle Up)",
        "Намотування троса на зап'ястя (Wrist Roller / Side Wrist Pull / Isometric Wipers)",
        "Натиск плечима стоячи (Standing Palms-In Shoulder Press)",
        "Нахили гуд морнінг зі штангою (Good Morning)",
        "Нахили гуд морнінг з резинкою (Band Good Morning (Pull Through))",
        "Нахили тулуба в сторону на блоці (Single-arm high-cable side bend)",
        "Ножиці для ніг (Flutter Kicks)",
        "Обертання з диском російський твіст (Plate Twist / Russian twist)",
        "Олімпійські присідання (Olympic Squat)",
        "Опускання ніг у висі на шкарпетки (Hanging toes-to-bar)",
        "Опускання ніг у висі на прес (Hanging leg raise)",
        "Паралельні віджимання (Parallel Bar Dip)",
        "Паллоф прес (Pallof press)",
        "Перекочування з покришкою (Tire flip)",
        "Перенесення тачки (Rickshaw Carry)",
        "Перенесення ваги фермера (Dumbbell farmer's walk)",
        "Підйоми на біцепс зі штангою (Barbell Curl)",
        "Підйоми на біцепс з гантелями сидячи (Seated dumbbell biceps curl)",
        "Підйоми на біцепс з гантелями стоячи (Dumbbell Alternate Bicep Curl)",
        "Підйоми на литки стоячи (Standing Calf Raises)",
        "Підйоми на литки сидячи (Seated Calf Raise)",
        "Підйоми на литки в тренажері Сміта (Smith Machine Calf Raise)",
        "Підйоми на литки перекочуванням стоячи (Rocking Standing Calf Raise)",
        "Підйоми на литки в тренажері жим ногами (Calf Press)",
        "Підтягування (Pullups / Pull-up)",
        "Підтягування Роккі (Rocky Pull-Ups/Pulldowns)",
        "Підтягування зворотним хватом з куточком (Gorilla Chin/Crunch)",
        "Підтягування широким хватом за голову (Wide-Grip Rear Pull-Up)",
        "Підтягування V-подібним хватом (V-bar pull-up)",
        "Підтягування вниз головою (Upside-down pull-up)",
        "Підтягування з вагою (Weighted pull-up)",
        "Підтягування ніг до колін на турніку (Hanging Oblique Knee Raise)",
        "Планка на ліктях (Elbow plank)",
        "Планка класична (Plank)",
        "Поворот корпусу з міною (Landmine twist)",
        "Повороти корпусу на блоці знизу вгору (Standing cable low-to-high twist)",
        "Почерговий жим плечима з гантелями (Alternating standing shoulder press)",
        "Почерговий жим гантелей сидячи (Single-arm palm-in dumbbell shoulder press)",
        "Почерговий жим гантелей стоячи (Single-arm standing shoulder press)",
        "Почерговий підйом гантелей на біцепс з супінацією (Dumbbell Lying Supination)",
        "Присідання класичні (Barbell Squat / Squats)",
        "Присідання зі штангою на спині (Barbell Back Squat)",
        "Присідання зі штангою на спині на бокс (Barbell back squat to box / Smith machine box squat / Reverse Band Box Squat / Box Squat with Bands)",
        "Присідання зі штангою на грудях (Barbell front squat)",
        "Присідання кубок з гантеллю (Goblet Squat / Dumbbell Goblet Squat)",
        "Присідання з гантелями (Dumbbell squat)",
        "Присідання пістолетиком з гирею (Kettlebell Pistol Squat)",
        "Присідання в тренажері Гакк (Hack Squat / Narrow Stance Hack Squats)",
        "Присідання на одній нозі на глибину (Single-leg depth squat)",
        "Присідання колінами на підлозі зі штангою (Kneeling Squat)",
        "Присідання сиссі з вагою (Weighted sissy squat)",
        "Присідання зі штангою з ланцюгами (Squat with Chains)",
        "Присідання зі штангою з резинками (Reverse Band Box Squat)",
        "Присідання фронтальні з двома гирями (Front Squats With Two Kettlebells)",
        "Присідання у тренажері (Machine Squat)",
        "Присідання болгарські спліт зі штангою (Barbell Bulgarian split squat)",
        "Присідання спліт з гантелями (Split Squat with Dumbbells)",
        "Присідання вистрибуванням з вагою (Weighted Jump Squat / Arms-crossed jump squat)",
        "Пуловер з гантеллю з прямими руками (Straight-arm dumbbell pull-over)",
        "Рама жим плечима сидячи (Leverage Incline Chest Press / Leverage Chest Press / Leverage Decline Chest Press)",
        "Рак пулл зі штангою з резинками (Rack Pull with Bands)",
        "Розведення гантелей лежачи (Dumbbell Flyes)",
        "Розведення гантелей на похилій лаві (Incline Dumbbell Flyes)",
        "Розведення гантелей на спадаючій лаві (Decline Dumbbell Flyes)",
        "Розведення рук у кросовері на груди (Cable Crossover / Butterfly)",
        "Розведення рук у кросовері однією рукою (Single-arm cable cross-over)",
        "Розведення рук у тренажері на задню дельту (Seated rear delt fly)",
        "Розведення гантелей чаклун (Dumbbell spell caster)",
        "Розгинання ніг у тренажері (Leg Extensions)",
        "Розгинання ніг лежачи на фітболі (Exercise ball leg curl / Lying Leg Curls)",
        "Розгинання спини назад (Back extension)",
        "Розгинання рук на трицепс на блоці з мотузкою (Triceps Pushdown - Rope Attachment)",
        "Розгинання рук на трицепс на блоці з V-рукояткою (Cable V-bar push-down)",
        "Розгинання рук на трицепс на блоці зворотним хватом (Reverse Grip Triceps Pushdown)",
        "Розгинання рук на трицепс на блоці (Triceps Pushdown / Reverse Grip Triceps Pushdown)",
        "Розгинання рук на трицепс на блоці над головою (Low cable overhead triceps extension)",
        "Розгинання рук на трицепс з гантеллю сидячи (Standing Dumbbell Triceps Extension)",
        "Розгинання рук на трицепс з гантеллю лежачи (Decline Dumbbell Triceps Extension)",
        "Розгинання рук однією рукою на трицепс з гантеллю (One Arm Pronated Dumbbell Triceps Extension / One Arm Supinated Dumbbell Triceps Extension / Single-arm dumbbell triceps extension)",
        "Розгинання рук однією рукою на блоці на трицепс (Single-arm cable triceps extension / Standing One-Arm Dumbbell Triceps Extension)",
        "Роликовий прес (Ab Roller / Barbell Ab Rollout - On Knees / Barbell roll-out)",
        "Російський твіст (Russian twist)",
        "Румунська станова тяга (Romanian Deadlift)",
        "Румунська станова тяга з гантелями (Romanian Deadlift With Dumbbells)",
        "Румунська станова тяга з дефіциту (Romanian Deadlift from Deficit)",
        "Рухи руками та ногами на лижах (Skating)",
        "Сідничний місток зі штангою (Barbell glute bridge / Barbell Hip Thrust)",
        "Сідничний місток на одній нозі (Single-leg glute bridge / Glute bridge)",
        "Сідничний відмах ноги назад (Glute Kickback)",
        "Силові підйоми на дельту (Power Partials)",
        "Ситапи прес 3/4 (3/4 sit-up)",
        "Ситапи з підйомом штанги на лаві (Decline bar press sit-up)",
        "Стискання олімпійського диска руками (Standing Olympic Plate Hand Squeeze / Plate Pinch)",
        "Стрибки через скакалку (Jumping rope)",
        "Стрибки вбік з тумби (Side-to-side box skip)",
        "Стрибки ножиці (Scissors Jump)",
        "Сумо станова тяга (Sumo deadlift)",
        "Супермен (Superman)",
        "Т-гриф тяга з ручкою (T-Bar Row with Handle / T-Bar Row / Bent Over Two-Arm Long Bar Row)",
        "Тяга гантелей в нахилі (Dumbbell bent-over row)",
        "Тяга гантелей в нахилі на похилій лаві (Incline dumbbell row)",
        "Тяга гантелей в нахилі з долонями всередину (Bent Over Two-Dumbbell Row With Palms In)",
        "Тяга гантелі однією рукою (One-Arm Dumbbell Row)",
        "Тяга штанги в нахилі (Bent Over Barbell Row)",
        "Тяга штанги зворотним хватом (Yates Row Reverse Grip)",
        "Тяга штанги в нахилі на задню дельту (Barbell rear delt bent-over row)",
        "Тяга блоку до грудей (Lat pull-down)",
        "Тяга блоку до грудей зворотним хватом (Reverse-grip lat pull-down)",
        "Тяга блоку до грудей вузьким хватом (Close-Grip Front Lat Pulldown / Close-grip pull-down)",
        "Тяга Т-грифу (T-Bar Row)",
        "Тяга Т-грифу з ручкою (T-Bar Row with Handle)",
        "Тяга горизонтального блоку сидячи (Seated Cable Rows)",
        "Тяга штанги однією рукою (One-Arm Long Bar Row)",
        "Тяга однією рукою з нижнього блоку сидячи (Single-arm cable seated row)",
        "Тяга однією рукою з гирею (Single-arm kettlebell row)",
        "Тяга гирі поперемінно в упорі лежачи (Kettlebell alternating renegade row)",
        "Тяга в нахилі зворотним хватом (Reverse-grip bent-over row)",
        "Тяга штанги до підборіддя (Barbell upright row / Standing dumbbell upright row)",
        "Тяга штанги на груди з підлоги (Power clean / Clean / Hang Clean / Clean and press / Clean from Blocks / Power Clean from Blocks / Clean and jerk / Hang Clean - Below the Knees)",
        "Тяга саней ведмежою ходою (Bear crawl sled drag)",
        "Тяга лиця стоячи на блоці (Standing face pull / Seated face pull)",
        "Тяга штанги прямими руками вниз на блоці (Straight-Arm Pulldown / Straight-arm rope pull-down)",
        "Удари крос-джеб з гантелями сидячи (Dumbbell V-Sit Cross Jab)",
        "Утримання планки на ліктях (Elbow plank)",
        "Французький жим лежачи з EZ-грифом (EZ-Bar Skullcrusher / Incline EZ-bar skullcrusher / Decline EZ-bar skullcrusher)",
        "Французький жим гантелями (Dumbbell skullcrusher / Tricep Dumbbell Kickback / Double-arm triceps kick-back)",
        "Французький жим зі штангою за голову (Behind-the-head skullcrusher / Decline Close-Grip Bench To Skull Crusher)",
        "Французький жим лежачи вузьким хватом з EZ-грифом (Close-grip EZ-bar bench press)",
        "Французький жим лежачи з гантелями (Dumbbell skullcrusher)",
        "Французький жим з еластичною стрічкою (Band Skull Crusher)",
        "Фронтальний підйом гантелей перед собою (Dumbbell front raise)",
        "Ходьба випадами зі штангою (Barbell walking lunge)",
        "Чергування підйому дельт (Alternating Deltoid Raise)",
        "Чистий ривок штанги з вису (Hang Snatch / Power Snatch / Power snatch- / Power Clean from Blocks)",
        "Шраги зі штангою (Barbell shrug / Middle Back Shrug)",
        "Шраги в тренажері Сміта (Smith machine shrug)",
        "Шраги на важелі (Leverage Shrug)",
        "Шраги з гантелями (Standing dumbbell shrug)",
        "Шраги плечима в тренажері на литки (Calf-Machine Shoulder Shrug)",
        "Штовхання саней (Smith machine back squat / Axle Deadlift)",
        "Швунг жимовий штанги (Push-press / Single-arm kettlebell push-press / Single-arm kettlebell snatch / Clean and jerk / Kettlebell thruster)",
        "Ягодичний місток (Glute bridge)",
        "Ягодичний відмах (Glute Kickback)"
    ).sorted()
}
